"""add device_info to auth_sessions

Revision ID: 850a25312a2c
Revises: 7d4568fdb921
Create Date: 2026-05-04 13:36:18.535464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850a25312a2c'
down_revision: Union[str, Sequence[str], None] = '7d4568fdb921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('device_info', sa.String(length=200), nullable=True))
    op.add_column('auth_sessions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.create_index('ix_auth_sessions_access_token', 'auth_sessions', ['access_token'], unique=True)
    op.create_index('ix_auth_sessions_refresh_token', 'auth_sessions', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_sessions_refresh_token', table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_access_token', table_name='auth_sessions')
    op.drop_column('auth_sessions', 'ip_address')
    op.drop_column('auth_sessions', 'device_info')
    # ### end Alembic commands ###
